version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: flashpay-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: flashpay
      MYSQL_ROOT_PASSWORD: 0000
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - flashpay-net

  redis:
    image: redis:6.2
    container_name: flashpay-redis
    ports:
      - "6379:6379"
    networks:
      - flashpay-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: flashpay-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - flashpay-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: flashpay-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: flashpay-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - flashpay-net

  app:
    build: .
    container_name: flashpay-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - kafka
    networks:
      - flashpay-net

volumes:
  mysql-data:

networks:
  flashpay-net:
