name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 실행
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 코드
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # 3. Build the application with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t flashpay:latest .

      # 5. Push Docker image to Docker Hub (if you have a Docker Hub account)
      - name: Push Docker image to Docker Hub
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker tag flashpay:latest $DOCKER_USERNAME/flashpay:latest
          docker push $DOCKER_USERNAME/flashpay:latest

      # 6. Deploy to cloud (optional, here using a sample SSH deployment step)
      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$HOST "docker pull $DOCKER_USERNAME/flashpay:latest && docker-compose -f /path/to/docker-compose.yml up -d"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          HOST: ${{ secrets.HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
